services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - frontend  

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"

volumes:
  mongodb_data: